config/routes.rb
Rails.application.routes.draw do
  resources :mypokemons
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pokemon#index'
  get '/(:page)', to: 'pokemon#index'
  post 'pokemon/index/(:name)', to: 'pokemon#index'
  get 'pokemon/show/(:name)', to: 'pokemon#show'
  # get 'favorites/index', to: 'favorites#index'
  # post 'favorites/create', to: 'favorites#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mypokemon.rb
class Mypokemon < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/mypokemons_controller.rb
class MypokemonsController < ApplicationController
  before_action :set_mypokemon, only: %i[ show edit update destroy ]

  # GET /mypokemons or /mypokemons.json
  def index
    @mypokemons = Mypokemon.where(email: current_user.email)
    # @mypokemons = Mypokemon.all
  end

  # GET /mypokemons/1 or /mypokemons/1.json
  def show
  end

  # GET /mypokemons/new
  def new
    @mypokemon = Mypokemon.new
  end

  # GET /mypokemons/1/edit
  def edit
  end

  # POST /mypokemons or /mypokemons.json
  def create
    @mypokemon = Mypokemon.new(mypokemon_params)

    respond_to do |format|
      if @mypokemon.save
        format.html { redirect_to mypokemon_url(@mypokemon), notice: "Mypokemon was successfully created." }
        format.json { render :show, status: :created, location: @mypokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mypokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mypokemons/1 or /mypokemons/1.json
  def update
    respond_to do |format|
      if @mypokemon.update(mypokemon_params)
        format.html { redirect_to mypokemon_url(@mypokemon), notice: "Mypokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @mypokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mypokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mypokemons/1 or /mypokemons/1.json
  def destroy
    @mypokemon.destroy

    respond_to do |format|
      format.html { redirect_to mypokemons_url, notice: "Mypokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mypokemon
      @mypokemon = Mypokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mypokemon_params
      params.require(:mypokemon).permit(:name, :nickname, :image, :email)
    end
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
    require 'poke-api-v2'
    def index

        limit = 15 #initializing limit
        page = params.has_key?(:page) ? params[:page].to_i : 1 #get the currrennt page
        offset = (page - 1) * limit #determine the offset of data

        if(params.has_key?(:name) && !params[:name].blank?) #check wether the parameter name is set or not balnk
            @name = params[:name]   
            begin
                pokemon_list = PokeApi.get(pokemon: params[:name].downcase) #display the searched pokemon
            rescue => e
                @message = "No Results Found on #{params[:name]}" #display message when pokemon name is not in the data
            end
            @pokemons = pokemon_list 
        else
            pokemon_list = PokeApi.get(pokemon: {limit: limit, offset: offset}) #display all 15 pokemon

            pokemons_with_images = pokemon_list.results.map do |pokemon| #map the pokemon sprites
                details = PokeApi.get(pokemon: pokemon.name)
                {
                  name: pokemon.name,
                  image: details.sprites.front_default
                }
            end
    
            @pokemons = pokemons_with_images
        end
       
        @page = page
        # @pokemons.paginate
        # @pokemons = pokemons_with_images.paginate(page: page, per_page: limit, total_entries: 25)

    end

    def show
        pokemon = PokeApi.get(pokemon: params[:name].downcase)
        @pokemon = pokemon
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mypokemons_helper.rb
module MypokemonsHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="text-center">
    <p class="notice text-center"><%= notice %></p> 
    <p class="alert text-center"><%= alert %></p> 
    <% if user_signed_in? %> 
    <div class="text-center"> Welcome <%= current_user.email %> </div> 
      <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
    <% else %>
      <%= button_to "Sign in", new_user_session_path %> 
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/mypokemons/_form.html.erb
<%= form_with(model: mypokemon) do |form| %>
  <% if mypokemon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mypokemon.errors.count, "error") %> prohibited this mypokemon from being saved:</h2>

      <ul>
        <% mypokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div class="hidden">
      <label style="display: block" for="mypokemon_email">Email</label>
      <input type="text" name="mypokemon[email]" id="mypokemon_email" value="<%= current_user.email %>">
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mypokemons/_mypokemon.html.erb
<div id="<%= dom_id mypokemon %>">
  <p class="text-center">
    <strong>Name:</strong>
    <%= mypokemon.name %>
  </p>

  <p class="text-center">
    <strong>Nickname:</strong>
    <%= mypokemon.nickname %>
  </p>

  <p class="text-center">
    <strong>Owner:</strong>
    <%= mypokemon.email %>
  </p>

  <p class="text-center">
    <img src="<%= mypokemon.image %>">
  </p>

</div>

app/views/mypokemons/edit.html.erb
<h1>Editing mypokemon</h1>

<%= render "form", mypokemon: @mypokemon %>

<br>

<div>
  <%= link_to "Show this mypokemon", @mypokemon %> |
  <%= link_to "Back to mypokemons", mypokemons_path %>
</div>

app/views/mypokemons/index.html.erb
<h1>My Pokemons</h1>

<div id="mypokemons">
  <% @mypokemons.each do |mypokemon| %>
    <%= render mypokemon %>
    <p>
      <%= link_to "Manage Pokemon", mypokemon %>
    </p>
  <% end %>
</div>

<%= link_to "Create Pokemon", new_mypokemon_path %>
<p><%= link_to "Pokemon List", '/' %></p>

app/views/mypokemons/new.html.erb
<h1>New mypokemon</h1>

<%= render "form", mypokemon: @mypokemon %>

<br>

<div>
  <%= link_to "Back to mypokemons", mypokemons_path %>
</div>

app/views/mypokemons/show.html.erb
<%= render @mypokemon %>

<div>
  <%= link_to "Edit this Pokemon", edit_mypokemon_path(@mypokemon) %> |
  <%= link_to "Back to my Pokemons", mypokemons_path %>

  <%= button_to "Delete this Pokemon", @mypokemon, method: :delete %>
</div>

app/views/pokemon/index.html.erb
        <table cellpadding="10px" class="text-left">
            <tr>
                <td colspan="3" class="text-center">
                    <% if user_signed_in? %> 
                        <p><%= link_to "Go to my Pokemons", mypokemons_path %></p>
                    <% end %>
                    <form action="/">
                        <input placeholder="Search Pokemon by Name" value="" name="name">
                        <input type="submit" value="Search">
                    </form>
                </td>
            </tr>
            <tr>
                <td>Pokemon</td>
                <td>Name</td>
                <td></td>
            </tr>
            <% if @name.blank? %>
                <% @pokemons.each do |pokemon| %>
                    <tr>
                        <td>
                            <img src="<%= pokemon[:image] %>" alt="<%= pokemon[:name] %>">
                        </td>
                        <td>
                            <p><%= pokemon[:name].capitalize %></p>
                        </td>
                        <td>
                            <a href="/pokemon/show/<%= pokemon[:name].downcase %>">View</a> 
                            <% if user_signed_in? %> 
                                <form action="/mypokemons" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="wJwpX1bXuDYNgB0lODv25B8lWXi9F5yW8atkR_P1I3dSuTahkq9WDlBfGSTrmeql5ONib1FuyPdeJl6aaVckOg" autocomplete="off">

                                    <div class="hidden">
                                        <label style="display: block" for="mypokemon_name">Name</label>
                                        <input type="text" name="mypokemon[name]" id="mypokemon_name" value="<%= pokemon[:name].downcase %>">
                                    </div>

                                    <div class="hidden">
                                        <label style="display: block" for="mypokemon_nickname">Nickname</label>
                                        <input type="text" name="mypokemon[nickname]" id="mypokemon_nickname" value="<%= pokemon[:name].downcase %>">
                                    </div>

                                    <div class="hidden">
                                        <label style="display: block" for="mypokemon_image">Image</label>
                                        <input type="text" name="mypokemon[image]" id="mypokemon_image" value="<%= pokemon[:image] %>">
                                    </div>

                                    <div class="hidden">
                                        <label style="display: block" for="mypokemon_image">Image</label>
                                        <input type="text" name="mypokemon[image]" id="mypokemon_image" value="<%= pokemon[:image] %>">
                                    </div>
                                    
                                    <div class="hidden">
                                        <label style="display: block" for="mypokemon_email">Email</label>
                                        <input type="text" name="mypokemon[email]" id="mypokemon_email" value="<%= current_user.email %>">
                                    </div>

                                    <div>
                                        <input type="submit" name="commit" value="Add to favorites" data-disable-with="Create Mypokemon">
                                    </div>
                                </form>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
                <tr>
                    <td colspan="3" class="text-center">
                        <a href="/<%= (@page - 1) == 0 ? 1 : (@page - 1) %>">Prev</a> <a href="/<%= (@page + 1) %>">Next</a> 
                    </td>
                </tr>
            <% else %>
                <% if @message.blank? %>
                    <tr>
                        <td>
                            <img src="<%= @pokemons.sprites.front_default %>" alt="<%= @pokemons.name %>">
                        </td>
                        <td>
                            <p><%= @pokemons.name.capitalize %></p>
                        </td>
                        <td>
                            <a href="/pokemon/show/<%= @pokemons.name.downcase%>">View</a>
                            <% if user_signed_in? %> 
                                <form action="/mypokemons" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="wJwpX1bXuDYNgB0lODv25B8lWXi9F5yW8atkR_P1I3dSuTahkq9WDlBfGSTrmeql5ONib1FuyPdeJl6aaVckOg" autocomplete="off">

                                    <div class="hidden">
                                        <label style="display: block" for="mypokemon_name">Name</label>
                                        <input type="text" name="mypokemon[name]" id="mypokemon_name" value="<%= @pokemons.name.downcase %>">
                                    </div>

                                    <div class="hidden">
                                        <label style="display: block" for="mypokemon_nickname">Nickname</label>
                                        <input type="text" name="mypokemon[nickname]" id="mypokemon_nickname" value="<%= @pokemons.name.downcase %>">
                                    </div>

                                    <div class="hidden">
                                        <label style="display: block" for="mypokemon_image">Image</label>
                                        <input type="text" name="mypokemon[image]" id="mypokemon_image" value="<%= @pokemons.sprites.front_default %>">
                                    </div>

                                    <div class="hidden">
                                        <label style="display: block" for="mypokemon_email">Email</label>
                                        <input type="text" name="mypokemon[email]" id="mypokemon_email" value="<%= current_user.email %>">
                                    </div>

                                    <div>
                                        <input type="submit" name="commit" value="Add to favorites" data-disable-with="Create Mypokemon">
                                    </div>
                                </form>
                            <% end %>
                        </td>
                    </tr>
                <% else %>
                    <tr>
                        <td colspan="3"> <%= @message %> </td>
                    </tr>
                <% end %>
            <% end %>
        </table>

app/views/pokemon/show.html.erb
        <table cellpadding="10px" class="text-left">
            <tr>
                <td colspan="2" class="text-center">
                    <a href="/">Back</a>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="text-center">
                    <img src="<%= @pokemon.sprites.front_default %>" alt="<%= @pokemon.name %>">
                </td>
            </tr>
            <tr>
                <td>Name</td>
                <td><%= @pokemon.name.capitalize %></td>
            </tr>
            <tr>
                <td>Height</td>
                <td><%= @pokemon.height %></td>
            </tr>
            <tr>
                <td>Weight</td>
                <td><%= @pokemon.weight %></td>
            </tr>
            <tr>
                <td>Abilities</td>
                <td>
                    <% @pokemon.abilities.each do |ability| %>
                        <p><%= ability.ability.name.capitalize %></p>
                    <% end %>
                </td>
            </tr>
            <tr>
                <td>Held Items</td>
                <td>
                    <% @pokemon.held_items.each do |held| %>
                        <p><%= held.item.name.capitalize %></p>
                    <% end %>
                </td>
            </tr>
            <tr>
                <td>Moves</td>
                <td>
                    <ul>
                    <% @pokemon.moves.each do |move| %>
                        <li><%= move.move.name.capitalize %>,</li>
                    <% end %>
                    </ul>
                </td>
            </tr>
            <tr>
                <td>Stats</td>
                <td>
                    <% @pokemon.stats.each do |stat| %>
                        <p><%= stat.stat.name %>: <%= stat.base_stat %></p>
                    <% end %>
                </td>
            </tr>
            <tr>
                <td>Types</td>
                <td>
                    <% @pokemon.types.each do |type| %>
                        <p><%= type.type.name.capitalize %></p>
                    <% end %>
                </td>
            </tr>
        </table>